from typing import List
from .. import LogicalPlan
from ..common import DFSchema
from .base import Expr


class Aggregate:
    def group_by_exprs(self) -> List[Expr]: ...

    def aggregate_exprs(self) -> List[Expr]: ...

    def agg_expressions(self) -> List[Expr]: ...

    def agg_func_name(self, expr: Expr) -> str: ...

    def aggregation_arguments(self, expr: Expr) -> List[Expr]: ...

    def input(self) -> List[LogicalPlan]: ...

    def schema(self) -> DFSchema: ...
