from .base import Expr


class Not:
    def expr(self) -> Expr: ...

class IsNotNull:
    def expr(self) -> Expr: ...

class IsNull:
    def expr(self) -> Expr: ...

class IsTrue:
    def expr(self) -> Expr: ...

class IsFalse:
    def expr(self) -> Expr: ...

class IsUnknown:
    def expr(self) -> Expr: ...

class IsNotTrue:
    def expr(self) -> Expr: ...

class IsNotFalse:
    def expr(self) -> Expr: ...

class IsNotUnknown:
    def expr(self) -> Expr: ...

class Negative:
    def expr(self) -> Expr: ...
