from typing import List
from .. import LogicalPlan


class CreateMemoryTable:
    def name(self) -> str: ...
    def input(self) -> List[LogicalPlan]: ...
    def if_not_exists(self) -> bool: ...
    def or_replace(self) -> bool: ...
    def __name__(self) -> str: ...