from typing import List, Optional
from .. import LogicalPlan


class CreateView:
    def name(self) -> str: ...
    def input(self) -> List[LogicalPlan]: ...
    def or_replace(self) -> bool: ...
    def definition(self) -> Optional[str]: ...
    def __name__(self) -> str: ...
    