from typing import List
from .. import LogicalPlan


class DropTable:
    def name(self) -> str: ...

    def input(self) -> List[LogicalPlan]: ...

    def if_exists(self) -> bool: ...

    def __name__(self) -> str: ...
